-- 1. What are the details of all cars purchased in the year 2022?

SELECT DISTINCT c.*
FROM   sales s
       LEFT JOIN cars c
              ON c.car_id = s.car_id
WHERE  Year(purchase_date) = '2022'
ORDER  BY c.car_id ASC 

-- 2. What is the total number of cars sold by each salesperson?
SELECT s.salesman_id,
       sp.NAME,
       Count(s.car_id) 'Total'
FROM   sales s
       LEFT JOIN salespersons sp
              ON sp.salesman_id = s.salesman_id
GROUP  BY s.salesman_id,
          sp.NAME
ORDER  BY s.salesman_id,
          sp.NAME 

-- 3. What is the total revenue generated by each salesperson?
SELECT s.salesman_id,
       sp.NAME,
       Sum(c.cost_$) 'Revenue'
FROM   sales s
       LEFT JOIN salespersons sp
              ON sp.salesman_id = s.salesman_id
       LEFT JOIN cars c
              ON c.car_id = s.car_id
GROUP  BY s.salesman_id,
          sp.NAME
ORDER  BY s.salesman_id,
          sp.NAME 
-- 4.What are the details of the cars sold by each salesperson
SELECT
   name AS salesman,
   s.car_id,
   make,
   type,
   style,
   cost_$,
   purchase_date 
FROM
   sales s 
   JOIN
      cars c 
      ON s.car_id = c.car_id 
   JOIN
      salespersons sp 
      ON s.salesman_id = sp.salesman_id 
ORDER BY
   salesman,
   purchase_date DESC;
-- 5. What is the total revenue generated by each car type?
SELECT c.type
       Sum(c.cost_$) 'Revenue'
FROM   sales s
       LEFT JOIN salespersons sp
              ON sp.salesman_id = s.salesman_id
       LEFT JOIN cars c
              ON c.car_id = s.car_id
GROUP  BY s.salesman_id,
          sp.NAME
ORDER  BY s.salesman_id,
          sp.NAME 
