-- 1. What are the details of all cars purchased in the year 2022?

SELECT DISTINCT c.*
FROM   sales s
       LEFT JOIN cars c
              ON c.car_id = s.car_id
WHERE  Year(purchase_date) = '2022'
ORDER  BY c.car_id ASC 

-- 2. What is the total number of cars sold by each salesperson?
SELECT s.salesman_id,
       sp.NAME,
       Count(s.car_id) 'Total'
FROM   sales s
       LEFT JOIN salespersons sp
              ON sp.salesman_id = s.salesman_id
GROUP  BY s.salesman_id,
          sp.NAME
ORDER  BY s.salesman_id,
          sp.NAME 

-- 3. What is the total revenue generated by each salesperson?
SELECT s.salesman_id,
       sp.NAME,
       Sum(c.cost_$) 'Revenue'
FROM   sales s
       LEFT JOIN salespersons sp
              ON sp.salesman_id = s.salesman_id
       LEFT JOIN cars c
              ON c.car_id = s.car_id
GROUP  BY s.salesman_id,
          sp.NAME
ORDER  BY s.salesman_id,
          sp.NAME 
-- 4.What are the details of the cars sold by each salesperson
SELECT
   name AS salesman,
   s.car_id,
   make,
   type,
   style,
   cost_$,
   purchase_date 
FROM
   sales s 
   JOIN
      cars c 
      ON s.car_id = c.car_id 
   JOIN
      salespersons sp 
      ON s.salesman_id = sp.salesman_id 
ORDER BY
   salesman,
   purchase_date DESC;
-- 5. What is the total revenue generated by each car type?
SELECT c.type
       Sum(c.cost_$) 'Revenue'
FROM   sales s
       LEFT JOIN salespersons sp
              ON sp.salesman_id = s.salesman_id
       LEFT JOIN cars c
              ON c.car_id = s.car_id
GROUP  BY s.salesman_id,
          sp.NAME
ORDER  BY s.salesman_id,
          sp.NAME 
--6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
SELECT DISTINCT c.*
FROM            sales s
LEFT JOIN       cars c
ON              c.car_id=s.car_id
LEFT JOIN       salespersons p
ON              p.salesman_id=s.salesman_id
WHERE           Year(purchase_date)='2021'
AND             p.NAME='Emily Wong'
ORDER BY        c.car_id ASC
       
--7. What is the total revenue generated by the sales of hatchback cars?
SELECT    Sum(c.cost_$) 'Revenue'
FROM      sales s
LEFT JOIN cars c
ON        c.car_id=s.car_id
WHERE     c.style='hatchback' 
       
--8. what IS the total revenue generated BY the sales OF suv cars IN the year 2022?
SELECT    Sum(c.cost_$) 'Revenue'
FROM      sales s
LEFT JOIN cars c
ON        c.car_id=s.car_id
WHERE     c.style='SUV'
AND       Year(purchase_date)='2022'
       
-- 9. what IS the NAME AND city OF the salesperson who sold the most number OF cars IN the year 2023?
WITH cte1 AS
          (
                   SELECT   s.salesman_id,
                            rank() OVER (ORDER BY count(car_id) DESC ) rank
                   FROM     sales s
                   WHERE    year(purchase_date)='2023'
                   GROUP BY s.salesman_id )
SELECT p.NAME,
        p.city
 FROM   salespersons p
 WHERE  p.salesman_id IN
        (
               SELECT salesman_id
               FROM   cte1
               WHERE  rank=1) 
       
--10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
WITH cte1 AS
       (
                 SELECT    s.salesman_id ,
                           rank() OVER (ORDER BY sum(cost_$) DESC ) rank
                 FROM      sales s
                 LEFT JOIN cars c
                 ON        c.car_id=s.car_id
                 WHERE     year(purchase_date)='2022'
                 GROUP BY  s.salesman_id )
SELECT p.NAME,
       p.age
FROM   salespersons p
WHERE  p.salesman_id IN
       (
              SELECT salesman_id
              FROM   cte1
              WHERE  rank=1)
